# This file is a template, and might need editing before it works on your project.
image: docker:latest
stages: 
  - build
services:
  - docker:dind
before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - export
  
rnaseq-drake:
  stage: build
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_BUILD_NAME}
  script:
    - docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME} rnaseq-drake
    - docker tag ${IMAGE_NAME} ${IMAGE_NAME}
    - docker run ${IMAGE_NAME} R --version
    - docker push ${CI_REGISTRY_IMAGE}:r

rnaseq-drake-mro:
  stage: build
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_BUILD_NAME}
  script:
    - docker build --pull --cache-from ${IMAGE_NAME} -t ${IMAGE_NAME} rnaseq-drake-mro
    - docker tag ${IMAGE_NAME} ${IMAGE_NAME}
    - docker run ${IMAGE_NAME} R --version
    - docker push ${CI_REGISTRY_IMAGE}:mro