image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

rnaseq-drake:
  stage: build
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_BUILD_NAME}
  script:
    - docker build --pull ${IMAGE_NAME} -t ${IMAGE_NAME}
    - docker run ${IMAGE_NAME} Rscript
    - docker push ${IMAGE_NAME}