
library(tidyverse)
library(rlang)
library(magrittr)
library(pheatmap)
library(kableExtra)
library(IRdisplay)
library(janitor)
library(RColorBrewer)
library(paletteer)
library(readxl)
library(cowplot)
library(irlba)
library(ggforce)
library(uwot)
library(formattable)
library(drake)

library(DESeq2)
library(tximport)
library(moduleScoreR)
library(flyio)
library(inspectdf)
library(BiocParallel)
library(genefilter)
